/** 사투리 가사 맞추기용 데이터: 장르·곡정보·원문 가사·사투리 가사 */
export interface DialectLyric {
  genre: string;
  title: string;
  artist: string;
  original: string;
  dialect: string;
}

const GENRE = {
  BALLAD: "발라드",
  KPOP: "K-pop",
  JPOP: "J-pop",
  POP: "팝송",
  DANCE: "댄스",
  INDIE: "인디",
  RNB: "R&B",
  HIPHOP: "힙합",
} as const;

export const dialectLyrics: DialectLyric[] = [
  // 1. 발라드
  { genre: GENRE.BALLAD, title: "0+0", artist: "한로로", original: "영 더하기 영은 영이건만 우린 뭐라도 될 줄 알았나 봐", dialect: "빵 더하기 빵은 빵인데, 우리는 뭐라도 될 줄 알았는갑네" },
  { genre: GENRE.BALLAD, title: "Love Wins All", artist: "아이유", original: "일부러 나란히 길 잃은 우리 두 사람", dialect: "일부러 나란히 길 잃어뿐 우리 두 사람 아인가" },
  { genre: GENRE.BALLAD, title: "그대만 있다면", artist: "너드커넥션", original: "그대만 있다면 세상 모든 걸 다 가진 기분일 텐데", dialect: "니만 있다 카면 세상 천지 다 가진 기분일 낀데" },
  { genre: GENRE.BALLAD, title: "헤어지자 말해요", artist: "박재정", original: "헤어지자 말해요 오늘이 지나면 우린 볼 수 없게", dialect: "헤어지자 안 카나, 오늘 지나면 우리는 인자 몬 본데이" },
  { genre: GENRE.BALLAD, title: "사랑은 늘 도망가", artist: "임영웅", original: "사랑은 늘 도망가 잠시 쉬어가면 좋을 텐데", dialect: "사랑은 맨날 도망간데이, 잠시 쉬어가면 억수로 좋을 낀데" },
  { genre: GENRE.BALLAD, title: "인사", artist: "범진", original: "안녕이라고 말하지 마 나를 떠나지 마", dialect: "안녕이라카지 마라, 내를 떠나지 마라 쫌" },
  { genre: GENRE.BALLAD, title: "모래 알갱이", artist: "임영웅", original: "나는 작은 바람에도 흩어질 조그만 모래 알갱이", dialect: "내는 쪼매난 바람에도 날라댕기는 조그만 모래 알갱이다" },
  { genre: GENRE.BALLAD, title: "잠시라도 우리", artist: "성시경, 나얼", original: "잠시라도 우리 함께였던 그 시절을 잊지 못해요", dialect: "잠시라도 우리 같이 있었던 그 시절을 몬 잊는데이" },
  { genre: GENRE.BALLAD, title: "잘 지내자, 우리", artist: "최유리", original: "잘 지내자 우리 아프지 말고", dialect: "잘 지내자 우리, 아프지 말고 단디 하고" },
  { genre: GENRE.BALLAD, title: "주저하는 연인들을 위해", artist: "잔나비", original: "추억할 그 밤이 안 올 것 같아", dialect: "추억할 그 밤이 안 올 것 같다 안 카나" },
  { genre: GENRE.BALLAD, title: "취중고백", artist: "김민석 (멜로망스)", original: "취기를 빌려 오늘 너에게 고백할 거야", dialect: "술 기운 좀 빌리가꼬 오늘 니한테 고백할끼다" },
  { genre: GENRE.BALLAD, title: "너의 모든 순간", artist: "성시경", original: "너의 모든 순간 그게 나였으면 좋겠다", dialect: "니 모든 순간에 그기 내였으면 좋겠데이" },
  { genre: GENRE.BALLAD, title: "어떻게 이별까지 사랑하겠어, 널 사랑하는 거지", artist: "AKMU", original: "어떻게 이별까지 사랑하겠어 널 사랑하는 거지", dialect: "우째 이별까지 사랑하겠노, 니를 사랑하는 기지" },
  { genre: GENRE.BALLAD, title: "좋니", artist: "윤종신", original: "좋니 사랑해서 사랑을 시작할 때", dialect: "좋나? 사랑해서 사랑 시작할 때 말이다" },
  { genre: GENRE.BALLAD, title: "모든 날, 모든 순간", artist: "폴킴", original: "모든 날 모든 순간 함께해", dialect: "모든 날 모든 순간 같이 하자" },
  { genre: GENRE.BALLAD, title: "예뻤어", artist: "DAY6", original: "예뻤어 날 바라봐 주던 그 눈빛", dialect: "이뻤데이, 내 쳐다보던 그 눈깔" },
  { genre: GENRE.BALLAD, title: "해요", artist: "#안녕", original: "그녀와 난 결혼을 해요", dialect: "가스나 가랑 내랑 결혼한데이" },
  { genre: GENRE.BALLAD, title: "비의 랩소디", artist: "임재현", original: "내게 소중한 건 너뿐이야", dialect: "내한테 중한 거는 니뿐이데이" },
  { genre: GENRE.BALLAD, title: "사랑인가 봐", artist: "멜로망스", original: "사랑인가 봐 무얼 해도 신나고", dialect: "사랑인갑다, 뭘 해도 신나노" },
  { genre: GENRE.BALLAD, title: "첫 눈", artist: "EXO", original: "너를 만나면 눈물 차올라", dialect: "니 만나면 눈물이 차오른다 아이가" },
  // 2. K-pop
  { genre: GENRE.KPOP, title: "Supernova", artist: "에스파", original: "사건은 다가와 Ah Oh Ay", dialect: "큰일이 다가온다 안 카나 Ah Oh Ay" },
  { genre: GENRE.KPOP, title: "Magnetic", artist: "아일릿", original: "You You You You like it's magnetic", dialect: "니 니 니 니 억수로 땡긴다 자석 맹키로" },
  { genre: GENRE.KPOP, title: "해야", artist: "아이브", original: "해야 해야 해야 한 입에 널 삼킬 때야", dialect: "해야 해야 해야 한 입에 니를 확 삼킬 때다" },
  { genre: GENRE.KPOP, title: "Armageddon", artist: "에스파", original: "거침없이 난 널 이끌어", dialect: "거침없이 내는 니를 끄시 당겨" },
  { genre: GENRE.KPOP, title: "나는 아픈 건 딱 질색이니까", artist: "(여자)아이들", original: "나는 아픈 건 딱 질색이니까 오늘 하루도 잘 부탁해", dialect: "내는 아픈 거는 억수로 질색이다 아이가, 오늘 하루도 잘 부탁한데이" },
  { genre: GENRE.KPOP, title: "Hype Boy", artist: "NewJeans", original: "Cuz I know what you like boy", dialect: "내 니 뭐 좋아하는지 안다 머스마야" },
  { genre: GENRE.KPOP, title: "Ditto", artist: "NewJeans", original: "말해줘 Say it back", dialect: "말해도, 니도 말해바라" },
  { genre: GENRE.KPOP, title: "EASY", artist: "LE SSERAFIM", original: "쉽지 않음 내가 쉽게 easy", dialect: "쉽지 않아도 내가 쉽게 맹근다 easy" },
  { genre: GENRE.KPOP, title: "Smart", artist: "LE SSERAFIM", original: "I'm a smarter baby", dialect: "내가 더 똑디다 야야" },
  { genre: GENRE.KPOP, title: "첫 만남은 계획대로 되지 않아", artist: "TWS", original: "첫 만남은 너무 어려워", dialect: "첫 만남은 억수로 어렵데이" },
  { genre: GENRE.KPOP, title: "Love 119", artist: "RIIZE", original: "뺏긴 내 맘이 다시 119", dialect: "뺏긴 내 맘이 또 119다 마" },
  { genre: GENRE.KPOP, title: "Drama", artist: "에스파", original: "I bring I bring all the Drama", dialect: "내가 다 가온다 드라마" },
  { genre: GENRE.KPOP, title: "Baddie", artist: "아이브", original: "I'm a pretty little baddie", dialect: "나는 쫌 이쁜 나쁜 가스나다" },
  { genre: GENRE.KPOP, title: "I AM", artist: "아이브", original: "너는 누군가 필요해", dialect: "니는 누가 필요하다 아이가" },
  { genre: GENRE.KPOP, title: "ETA", artist: "NewJeans", original: "What's your ETA?", dialect: "니 언제 도착하노?" },
  { genre: GENRE.KPOP, title: "Seven", artist: "정국", original: "Every hour every minute every second", dialect: "매 시간 매 분 매 초마다 말이다" },
  { genre: GENRE.KPOP, title: "Standing Next to You", artist: "정국", original: "Standing next to you", dialect: "니 옆에 서 있다 안 카나" },
  { genre: GENRE.KPOP, title: "음악의 신", artist: "세븐틴", original: "음악의 신이 있다면 이건 당신에게 주는 메시지", dialect: "음악의 신이 있다 카면 이건 님한테 주는 전갈이요" },
  { genre: GENRE.KPOP, title: "손오공", artist: "세븐틴", original: "마치 된 것 같아 손오공", dialect: "마치 된 것 같다 손오공" },
  { genre: GENRE.KPOP, title: "MANIAC", artist: "Stray Kids", original: "나사 빠진 것처럼 미쳐", dialect: "나사 빠진 거 맹키로 미치라" },
  // 3. J-pop
  { genre: GENRE.JPOP, title: "Bling-Bang-Bang-Born", artist: "Creepy Nuts", original: "누구도 손댈 수 없는 mirror", dialect: "아무도 손 못 댄다 거울 아이가" },
  { genre: GENRE.JPOP, title: "Idol (아이돌)", artist: "YOASOBI", original: "넌 완벽한 궁극의 아이돌", dialect: "니는 억수로 완벽한 끝판왕 아이돌" },
  { genre: GENRE.JPOP, title: "NIGHT DANCER", artist: "imase", original: "어떻게 되든 상관없어 그저 춤추자", dialect: "뭐 우째 되든 상관없다 그냥 춤이나 추자" },
  { genre: GENRE.JPOP, title: "Lemon", artist: "요네즈 켄시", original: "지금도 당신은 나의 빛", dialect: "지금도 당신은 내 빛이데이" },
  { genre: GENRE.JPOP, title: "Betelgeuse", artist: "유우리", original: "베텔기우스가 떨리는 노래를", dialect: "베텔기우스가 떨리는 노래를 마" },
  { genre: GENRE.JPOP, title: "Shinunoga E-wa (죽는 게 나아)", artist: "후지이 카제", original: "당신 없이는 난 죽는 게 나아", dialect: "니 없이는 내 죽는 게 낫데이" },
  { genre: GENRE.JPOP, title: "Kick Back", artist: "요네즈 켄시", original: "행복해 럭키", dialect: "행복하다 억수로 운 좋네" },
  { genre: GENRE.JPOP, title: "사랑을 전하고 싶다던가", artist: "아이묭", original: "사랑을 전하고 싶다던가 말하고 있어", dialect: "사랑을 전하고 싶다 카면서 말하고 있네" },
  { genre: GENRE.JPOP, title: "괴수으 꽃노래", artist: "Vaundy", original: "소동을 일으켜 줘", dialect: "난리 좀 피아 도" },
  { genre: GENRE.JPOP, title: "Overdose", artist: "natori", original: "해 볼 텐가? 해 볼 텐가?", dialect: "해 볼 끼가? 해 볼 끼가?" },
  { genre: GENRE.JPOP, title: "Blue", artist: "YOASOBI", original: "아아, 지루한 나날들에", dialect: "아따, 지루한 날들에" },
  { genre: GENRE.JPOP, title: "Dry Flower", artist: "유우리", original: "아마도 아직 너를 좋아해", dialect: "아마도 아직 니 좋아한데이" },
  { genre: GENRE.JPOP, title: "Marigold", artist: "아이묭", original: "밀짚모자의 여름이 흔들려", dialect: "밀짚모자의 여름이 흔들린데이" },
  { genre: GENRE.JPOP, title: "Pretender", artist: "Official Hige Dandism", original: "너의 운명의 사람은 내가 아니야", dialect: "니 운명의 머스마는 내가 아이다" },
  { genre: GENRE.JPOP, title: "Show", artist: "Ado", original: "자, 보여 줄게", dialect: "자, 함 봐라" },
  { genre: GENRE.JPOP, title: "Specialz", artist: "King Gnu", original: "You are my special", dialect: "니는 내한테 특별하데이" },
  { genre: GENRE.JPOP, title: "First Love", artist: "우타다 히카루", original: "언제나 당신은 그대로 있어 줘", dialect: "맨날 천날 니는 고대로 있어라" },
  { genre: GENRE.JPOP, title: "Nandemonaiya (아무것도 아니야)", artist: "RADWIMPS", original: "우리들 사이를 스쳐 지나간 바람은", dialect: "우리 사이를 스쳐 지나간 바람 그거는" },
  { genre: GENRE.JPOP, title: "Stay With Me", artist: "마츠바라 미키", original: "내 곁에 있어 줘", dialect: "내 옆에 딱 붙어 있어라" },
  { genre: GENRE.JPOP, title: "Kimino Toriko (Summertime)", artist: "Maggie", original: "너의 포로가 되어버려", dialect: "니한테 꽉 잡혀뿟다" },
  // 4. 팝송
  { genre: GENRE.POP, title: "Espresso", artist: "Sabrina Carpenter", original: "That's that me espresso", dialect: "그게 바로 내다 에스프레소" },
  { genre: GENRE.POP, title: "Die With A Smile", artist: "Lady Gaga, Bruno Mars", original: "If the world was ending", dialect: "세상이 작살난다 카면" },
  { genre: GENRE.POP, title: "Beautiful Things", artist: "Benson Boone", original: "I want you, I need you, oh God", dialect: "내는 니 원하고 니 필요하다, 아이고 맙소사" },
  { genre: GENRE.POP, title: "Cruel Summer", artist: "Taylor Swift", original: "It's a cruel summer With you", dialect: "억수로 잔인한 여름이데이 니랑 함께라서" },
  { genre: GENRE.POP, title: "Dangerously", artist: "Charlie Puth", original: "I loved you dangerously", dialect: "내 니 겁나게 사랑했데이" },
  { genre: GENRE.POP, title: "Unholy", artist: "Sam Smith, Kim Petras", original: "Mummy don't know daddy's getting hot", dialect: "엄니는 모른다 아부지 뜨거워지는 거" },
  { genre: GENRE.POP, title: "As It Was", artist: "Harry Styles", original: "You know it's not the same as it was", dialect: "니도 알제 옛날 같지 않다는 거" },
  { genre: GENRE.POP, title: "Flowers", artist: "Miley Cyrus", original: "I can buy myself flowers", dialect: "꽃은 내 돈으로 살 수 있데이" },
  { genre: GENRE.POP, title: "Stay", artist: "The Kid LAROI, Justin Bieber", original: "I do the same thing I told you that I never would", dialect: "절대 안 한다 캐놓고 똑같은 짓 또 하고 있네" },
  { genre: GENRE.POP, title: "I Don't Think That I Like Her", artist: "Charlie Puth", original: "I don't think that I like her", dialect: "내 갸 안 좋아하는 거 같다" },
  { genre: GENRE.POP, title: "Anti-Hero", artist: "Taylor Swift", original: "It's me, hi, I'm the problem, it's me", dialect: "내다, 안녕, 내가 문제다, 내라니까" },
  { genre: GENRE.POP, title: "Made You Look", artist: "Meghan Trainor", original: "I could have my Gucci on", dialect: "내 구찌 걸칠 수 있었다 아이가" },
  { genre: GENRE.POP, title: "Snooze", artist: "SZA", original: "I can't lose when I'm with you", dialect: "니랑 있으면 내는 절대 안 진다" },
  { genre: GENRE.POP, title: "Vampire", artist: "Olivia Rodrigo", original: "Bloodsucker, fame fucker", dialect: "피 빨아묵는 놈, 인기만 밝히는 놈" },
  { genre: GENRE.POP, title: "Greedy", artist: "Tate McRae", original: "I would want myself", dialect: "내라도 내가 탐나겠네" },
  { genre: GENRE.POP, title: "Paint The Town Red", artist: "Doja Cat", original: "I said what I said", dialect: "내가 뱉은 말은 뱉은 기다" },
  { genre: GENRE.POP, title: "Water", artist: "Tyla", original: "Make me sweat, make me hotter", dialect: "땀 나게 해 봐라, 더 뜨겁게 해 봐라" },
  { genre: GENRE.POP, title: "Bad Habit", artist: "Steve Lacy", original: "I wish I knew you wanted me", dialect: "니가 내 원한 거 알았으면 좋았을 낀데" },
  { genre: GENRE.POP, title: "Kiss Me More", artist: "Doja Cat", original: "Can you kiss me more?", dialect: "뽀뽀 쪼매 더 해주면 안 되나?" },
  { genre: GENRE.POP, title: "Levitating", artist: "Dua Lipa", original: "You want me, I want you, baby", dialect: "니 내 원하고, 내 니 원한다 가스나야" },
  // 5. 댄스
  { genre: GENRE.DANCE, title: "Smoke", artist: "다이나믹 듀오, 이영지", original: "나는 달리거나 넘어지거나", dialect: "내는 달리거나 자빠지거나 한다" },
  { genre: GENRE.DANCE, title: "Guilty", artist: "태민", original: "유죄인 걸 알면서도 네 맘을 훔쳐", dialect: "죄 지은 거 알면서도 니 맘을 쌔비가네" },
  { genre: GENRE.DANCE, title: "Get A Guitar", artist: "RIIZE", original: "Get get get a guitar", dialect: "기타 하나 가온나 마" },
  { genre: GENRE.DANCE, title: "Fast Forward", artist: "전소미", original: "How many lovers do I go through", dialect: "사랑을 얼매나 더 해야 되노" },
  { genre: GENRE.DANCE, title: "Shoong!", artist: "태양 (feat. LISA)", original: "너에게로 슈웅", dialect: "니한테로 슈웅 날라간데이" },
  { genre: GENRE.DANCE, title: "Super Shy", artist: "NewJeans", original: "I'm super shy, super shy", dialect: "내는 억수로 부끄럽다, 억수로" },
  { genre: GENRE.DANCE, title: "Rover", artist: "카이", original: "Mr. Rover rover rover", dialect: "미스터 로버 로버 로버야" },
  { genre: GENRE.DANCE, title: "Spicy", artist: "에스파", original: "I'm too spicy for your heart", dialect: "내 니 심장에 억수로 맵데이" },
  { genre: GENRE.DANCE, title: "Queencard", artist: "(여자)아이들", original: "I'm a Queencard", dialect: "내가 바로 퀸카다" },
  { genre: GENRE.DANCE, title: "Chili", artist: "화사", original: "매운 거 좀 더 줘", dialect: "매운 거 쫌 더 도라" },
  { genre: GENRE.DANCE, title: "Baggy Jeans", artist: "NCT U", original: "In my baggy baggy baggy jeans", dialect: "내 헐렁한 청바지 입고 말이다" },
  { genre: GENRE.DANCE, title: "CAKE", artist: "ITZY", original: "ITZY ITZY like that", dialect: "있지 있지 그래가지고" },
  { genre: GENRE.DANCE, title: "Bubble", artist: "STAYC", original: "잔소리는 Bubble bubble bubble", dialect: "잔소리는 거품이다 거품" },
  { genre: GENRE.DANCE, title: "S-Class", artist: "Stray Kids", original: "가장 빛나는 별", dialect: "제일 빤짝이는 별 아이가" },
  { genre: GENRE.DANCE, title: "Bouncy", artist: "ATEEZ", original: "좀 더 매운맛을 보여 줄게", dialect: "쫌 더 매운맛을 뷔줄게" },
  { genre: GENRE.DANCE, title: "UNFORGIVEN", artist: "LE SSERAFIM", original: "Unforgiven I'm a villain", dialect: "용서 못 받는데이 나는 빌런이다" },
  { genre: GENRE.DANCE, title: "Fighting (파이팅 해야지)", artist: "부석순", original: "파이팅 해야지", dialect: "단디 해야지" },
  { genre: GENRE.DANCE, title: "Candy", artist: "NCT DREAM", original: "단지 널 사랑해", dialect: "그냥 니 사랑한데이" },
  { genre: GENRE.DANCE, title: "POP!", artist: "나연", original: "Pop pop pop 터트려", dialect: "팝 팝 팝 터자뿌라" },
  { genre: GENRE.DANCE, title: "Next Level", artist: "에스파", original: "I'm on the next level", dialect: "내는 차원이 다르다 안 카나" },
  // 6. 인디
  { genre: GENRE.INDIE, title: "밤양갱", artist: "비비 (BIBI)", original: "달디달고 달디단 밤양갱", dialect: "억수로 달달구리한 밤양갱" },
  { genre: GENRE.INDIE, title: "Discord", artist: "QWER", original: "불협화음이 아니야 우리만의 서사야", dialect: "불협화음 그기 아이다 우리만의 이야기다 안 카나" },
  { genre: GENRE.INDIE, title: "No Pain", artist: "실리카겔", original: "내가 만든 집에서 모두 함께 노래를 합시다 No pain", dialect: "내가 지은 집구석에서 다 같이 노래나 부르입시다 아픈 거 없이" },
  { genre: GENRE.INDIE, title: "Love Lee", artist: "AKMU", original: "So lovely day so lovely", dialect: "억수로 사랑스런 날이다" },
  { genre: GENRE.INDIE, title: "후라이의 꿈", artist: "AKMU", original: "저 거위도 벽을 넘어 하늘을 날을 거라고", dialect: "저 거위 저것도 벽 넘어가꼬 날라댕긴다 카고" },
  { genre: GENRE.INDIE, title: "그라데이션", artist: "10CM", original: "나의 하루는 다 너로 가득해", dialect: "내 하루는 싹 다 니로 꽉 찼데이" },
  { genre: GENRE.INDIE, title: "부동의 첫사랑", artist: "10CM", original: "어설픈 안부마저 건네지 못하고", dialect: "어설픈 안부조차 못 묻고 있네" },
  { genre: GENRE.INDIE, title: "스토커", artist: "10CM", original: "나도 알아 나의 문제가 무엇인지", dialect: "내도 안다 내 문제가 뭔지" },
  { genre: GENRE.INDIE, title: "사랑끼리", artist: "최유리", original: "우린 서로 사랑을 했고", dialect: "우린 서로 사랑을 했었고" },
  { genre: GENRE.INDIE, title: "Antifreeze", artist: "백예린 (원곡: 검정치마)", original: "우린 오래전부터 어쩔 수 없는 거였어", dialect: "우린 옛날부터 어쩔 수 없는 기였다" },
  { genre: GENRE.INDIE, title: "건물 사이에 피어난 장미", artist: "H1-KEY (하이키)", original: "건물 사이에 피어난 장미", dialect: "건물 틈바구니에 핀 장미꽃" },
  { genre: GENRE.INDIE, title: "긴 꿈", artist: "새소년", original: "긴 꿈을 꾸었어", dialect: "긴 꿈을 꿨다 아이가" },
  { genre: GENRE.INDIE, title: "주저하는 연인들을 위해", artist: "잔나비", original: "초록을 거머쥔 우리는", dialect: "초록색을 꽉 쥔 우리는 말이다" },
  { genre: GENRE.INDIE, title: "Vancouver", artist: "BIG Naughty", original: "난 아직도 널 사랑해", dialect: "내는 아직도 니 사랑한데이" },
  { genre: GENRE.INDIE, title: "Bad", artist: "Wave To Earth", original: "How could you be so bad", dialect: "니 우째 그리 나쁠 수가 있노" },
  { genre: GENRE.INDIE, title: "Seasons", artist: "Wave To Earth", original: "I can't be your love", dialect: "내는 니 사랑이 몬 된다" },
  { genre: GENRE.INDIE, title: "서랍", artist: "10CM", original: "어린 날의 기억들을 꺼내어 본다", dialect: "어릴 때 기억들을 끄집어 내 본다" },
  { genre: GENRE.INDIE, title: "숲", artist: "최유리", original: "나는 내가 보여요", dialect: "내는 내가 보인데이" },
  { genre: GENRE.INDIE, title: "미류", artist: "한로로", original: "나의 사랑하는 미류나무야", dialect: "내 사랑하는 미류나무야" },
  { genre: GENRE.INDIE, title: "입술", artist: "한로로", original: "사랑한다는 말은 못 해도", dialect: "사랑한다 카는 말은 몬 해도" },
  // 7. R&B
  { genre: GENRE.RNB, title: "To. X", artist: "태연", original: "Gonna block you 불을 꺼 To. X", dialect: "니 차단해 뿐다 불 끈데이 엑스한테" },
  { genre: GENRE.RNB, title: "Die 4 You", artist: "DEAN (딘)", original: "I would die for you", dialect: "내는 니 위해 죽는다 안 카나" },
  { genre: GENRE.RNB, title: "Rush Hour", artist: "Crush", original: "이건 Traffic jam", dialect: "이거는 차 억수로 믹히네" },
  { genre: GENRE.RNB, title: "가을밤에 든 생각", artist: "잔나비", original: "멀리서 멀리서 멀리서 그대가 오네요", dialect: "멀리서 멀리서 멀리서 니가 온다 아이가" },
  { genre: GENRE.RNB, title: "Mantra", artist: "제니", original: "This that pretty girl mantra", dialect: "이게 이쁜 가스나들 주문이다" },
  { genre: GENRE.RNB, title: "BTBT", artist: "B.I", original: "비틀비틀거려 너 때문에", dialect: "비틀비틀한다 니 땜시로" },
  { genre: GENRE.RNB, title: "양화대교", artist: "Zion.T", original: "행복하자 우리 아프지 말고", dialect: "행복하자 우리 아프지 말고 쫌" },
  { genre: GENRE.RNB, title: "꺼내 먹어요", artist: "Zion.T", original: "이 노래를 초콜릿처럼 꺼내 먹어요", dialect: "이 노래를 초콜릿 맹키로 꺼내 무라" },
  { genre: GENRE.RNB, title: "비가 오는 날엔", artist: "헤이즈", original: "비가 오는 날엔 나를 찾아와", dialect: "비 오는 날에는 내 찾아온나" },
  { genre: GENRE.RNB, title: "헤픈 우연", artist: "헤이즈", original: "우연히라도 만나지 말자", dialect: "우연이라도 만나지 말자 쫌" },
  { genre: GENRE.RNB, title: "Square", artist: "백예린", original: "Come on let's go up to the stars", dialect: "퍼떡 온나 별 보러 가자" },
  { genre: GENRE.RNB, title: "Maybe It's Not Our Fault", artist: "백예린", original: "아마도 그건 우리 잘못은 아닐 거야", dialect: "아마 그건 우리 잘못은 아닐 끼다" },
  { genre: GENRE.RNB, title: "Alone", artist: "Crush", original: "혼자 남겨진 밤", dialect: "혼자 남겨진 밤이다" },
  { genre: GENRE.RNB, title: "나빠", artist: "Crush", original: "내가 나빠 아마 나빠", dialect: "내가 나쁘다 아마 나쁠끼다" },
  { genre: GENRE.RNB, title: "Instagram", artist: "DEAN", original: "문제야 문제 온 세상 속에", dialect: "문제다 문제 온 세상 천지에" },
  { genre: GENRE.RNB, title: "D (half moon)", artist: "DEAN", original: "너의 반의 반이라도", dialect: "니 반의 반이라도 말이다" },
  { genre: GENRE.RNB, title: "Love Lee", artist: "AKMU", original: "So lovely day", dialect: "억수로 사랑스런 날" },
  { genre: GENRE.RNB, title: "와르르", artist: "Colde", original: "내 마음이 와르르 무너져 내려요", dialect: "내 맘이 와르르 무너진다 안 카나" },
  { genre: GENRE.RNB, title: "자격지심", artist: "BE'O (feat. ZICO)", original: "네가 너무 예뻐서 그래", dialect: "니가 너무 이뻐가 그렇다" },
  { genre: GENRE.RNB, title: "Counting Stars", artist: "BE'O", original: "밤하늘에 펄 Better than your Louis Vuitton", dialect: "밤하늘에 펄 니 루이비통보다 낫데이" },
  // 8. 힙합
  { genre: GENRE.HIPHOP, title: "Small Girl", artist: "이영지", original: "Small girl, I stick with you", dialect: "쪼매난 가스나, 내 니한테 딱 붙을끼다" },
  { genre: GENRE.HIPHOP, title: "SPOT!", artist: "지코", original: "모두가 정신을 잃어가", dialect: "다들 정신 나간다 아이가" },
  { genre: GENRE.HIPHOP, title: "새삥", artist: "지코", original: "나는 새삥 모든 게 다 새삥", dialect: "내는 쌔거다 싹 다 쌔거다" },
  { genre: GENRE.HIPHOP, title: "마에스트로", artist: "창모", original: "다섯 살 때부터 나는 피아노를 쳤어 영재였지", dialect: "다섯 살 때부터 내는 피아노 쳤다 아이가 억수로 영재였다" },
  { genre: GENRE.HIPHOP, title: "VVS", artist: "미란이, 먼치맨 등", original: "내 삶은 빛나 VVS", dialect: "내 인생 빤짝인다 VVS" },
  { genre: GENRE.HIPHOP, title: "METEOR", artist: "창모", original: "정말 별거 아니었지", dialect: "진짜 별거 아니었데이" },
  { genre: GENRE.HIPHOP, title: "AEAO", artist: "다이나믹 듀오", original: "너와 내가 하나 되어", dialect: "니랑 내랑 하나 되가꼬" },
  { genre: GENRE.HIPHOP, title: "NOT SORRY", artist: "이영지", original: "I'm not sorry, I'm not sorry", dialect: "내 안 미안하다, 하나도 안 미안하데이" },
  { genre: GENRE.HIPHOP, title: "아무노래", artist: "지코", original: "아무 노래나 일단 틀어", dialect: "아무 노래나 일단 틀어라 쫌" },
  { genre: GENRE.HIPHOP, title: "Indigoy", artist: "JUSTHIS, Kid Milli 등", original: "We go high", dialect: "우리 위로 간데이" },
  { genre: GENRE.HIPHOP, title: "눈 (SNOW)", artist: "기리보이", original: "눈이 오네 눈이 와", dialect: "눈 온다 눈이 온다 아이가" },
  { genre: GENRE.HIPHOP, title: "호랑이소굴", artist: "기리보이", original: "호랑이 소굴에 들어온 것 같아", dialect: "호랑이 소굴에 들어온 거 같다" },
  { genre: GENRE.HIPHOP, title: "Melody", artist: "ASH ISLAND", original: "어디서 들려오는 Melody", dialect: "어데서 들려오는 멜로디고" },
  { genre: GENRE.HIPHOP, title: "Paranoid", artist: "ASH ISLAND", original: "난 매일 밤 혼자 있어", dialect: "내 맨날 밤에 혼자 있데이" },
  { genre: GENRE.HIPHOP, title: "지구오락실", artist: "이영지", original: "나는야 지구오락실", dialect: "내는 지구오락실이다" },
  { genre: GENRE.HIPHOP, title: "We Are", artist: "우원재", original: "We are we are we are", dialect: "우리가 우리가 우리가" },
  { genre: GENRE.HIPHOP, title: "거북선", artist: "팔로알토 등", original: "우린 거북선 다른 배들 통통", dialect: "우린 거북선이다 딴 배들은 통통배다" },
  { genre: GENRE.HIPHOP, title: "Good Day", artist: "PH-1 등", original: "Today is a good day", dialect: "오늘 억수로 좋은 날이네" },
  { genre: GENRE.HIPHOP, title: "시차", artist: "우원재", original: "밤새 모니터에 튀긴 침이", dialect: "밤새 모니터에 튀긴 침이 마" },
  { genre: GENRE.HIPHOP, title: "Band", artist: "창모", original: "돈 벌어라 밴드", dialect: "돈 벌어라 밴드야" },
];
